### ISSUE TITLE
libhid issue

### ISSUE THREAD

**Issue by ontran** [joergmlpts/bpm_bt#1]
Tried on Ubuntu 16, python 3.5, libhidapi-libusb.so.0 1.0.5:

$ python3 -c "import hid"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/hid/__init__.py", line 83, in <module>
    hidapi.hid_get_input_report.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t]
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0: undefined symbol: hid_get_input_report

**Comment by joergmlpts** [comment]
It works for me with Ubuntu 20 and Ubuntu 22.

**Comment by ontran** [comment]
i.c., time to upgrade to 22 then. Thanks very much! 
liyong
